# Generated by Django 4.2.1 on 2023-06-04 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_department_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
