# Generated by Django 4.2.1 on 2023-06-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_department_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
